### PR TITLE
New Netbox Version

### PR DESCRIPTION
**Pull request by xmariopereira**
Changed to the newest netbox version

https://hub.docker.com/r/ninech/netbox/tags/

### CODE REVIEW

**Comment by vishnoisuresh** [comment]
Hi Mario, 
We need to cross check the configuration files. In case there are updates.
Thanks

**Comment by xmariopereira** [comment]
Hi :) 

Just to tell you that i have changed it to run in GKE and to use 2.3.1 and is working :)

**Comment by vishnoisuresh** [comment]
Hi Mario, 
I am glad that you made it work on GKE. I checked the deployment file. you are having Netbox and Postgres containers in the same pod.  could you elaborate why you decided to have an only one pod instead of having different pods?
Thanks

**Comment by xmariopereira** [comment]
Well, this is just for testing purposes.

But with gke, your pvc must be in the same zone as your node and the pcv must be attached to the same node as your ngnix and postgres.
________________________________
De: suvi29 <notifications@github.com>
Enviado: 5 de março de 2018 09:57
Para: vishnoisuresh/netbox-kubernetes
Cc: Mário Pereira; Author
Assunto: Re: [vishnoisuresh/netbox-kubernetes] New Netbox Version (#3)


Hi Mario,
I am glad that you made it work on GKE. I checked the deployment file. you are having Netbox and Postgres containers in the same pod. could you elaborate why you decided to have an only one pod instead of having different pods?
Thanks

**Pull request closed without merging**
